const fs = require('node:fs');
const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');

const release = fs.readFileSync('app/release.html', 'utf8');
const command = fs.readFileSync('app/command-center.html', 'utf8');
const aibis = fs.readFileSync('app/aibis.html', 'utf8');
const css = fs.readFileSync('css/bizon-unified.css', 'utf8');
const overrides = fs.readFileSync('css/bizon-unified-overrides.css', 'utf8');
const script = fs.readFileSync('js/app-shell/unified-app.js', 'utf8');
const version = JSON.parse(fs.readFileSync('app/version.json', 'utf8'));

assert.match(release, /Business Simulation for Learning, Research and Strategy/);
assert.match(release, /Mô phỏng kinh doanh cho/);
assert.match(release, /THE BIZON ECOSYSTEM/);
assert.match(release, /How BizOn Works|Trò chơi hoạt động như thế nào/);
assert.match(release, /Command Center/);
assert.match(release, /Startup Lab/);
assert.match(release, /Brand Passport/);
assert.match(release, /AIBIS Global/);
assert.match(release, /Classroom/);
assert.match(release, /Analytics/);
assert.match(release, /Reports/);
assert.match(release, /Lumina/);
assert.match(release, /Decision Trace/);
assert.match(release, /Deterministic Engine/);
assert.match(release, /Open Science Ready/);
assert.match(release, /Market Attractiveness/);
assert.match(release, /74/);
assert.match(release, /18/);

for (const value of ['$12.45M', '$2.31M', '$4.28M', '18.6%', 'Medium', '82 / 100']) {
  assert.ok(command.includes(value), `Command Center missing sample metric ${value}`);
}
assert.match(command, /EcoFuture Team/);
assert.match(command, /Round 4/);
assert.match(command, /Lumina Coach/i);
assert.match(command, /Deterministic simulation core/);
assert.match(command, /Decision Trace/);
assert.match(command, /Classroom Ready/);
assert.match(command, /Web & PWA Access/);

assert.match(aibis, /bizon-unified-overrides\.css/);
assert.match(aibis, /href="\.\/command-center\.html"/);
assert.match(aibis, /entry-mode-engine\.js/);
assert.match(aibis, /country-profile-registry\.js/);
assert.match(aibis, /aibis-workspace\.js/);

assert.match(css, /--bz-bg:#030a14/);
assert.match(css, /\.bz-hero/);
assert.match(css, /\.bz-command-layout/);
assert.match(css, /@media\(max-width:650px\)/);
assert.match(overrides, /\.bz-modules/);
assert.match(overrides, /\.aibis-app/);
assert.match(script, /beforeinstallprompt/);
assert.match(script, /data-network-status/);
assert.match(script, /bizon-unified-overrides\.css/);
assert.equal(version.web_version, '1.1.0');
assert.equal(version.build_id, '2026.08.02.2');
assert.equal(version.force_refresh, false);

for (const text of ['auto-generated', 'Generated by', 'placeholder', 'Teaching demo', 'Android build pipeline']) {
  assert.ok(!release.includes(text), `Public release contains forbidden text: ${text}`);
  assert.ok(!command.includes(text), `Command Center contains forbidden text: ${text}`);
}

execFileSync(process.execPath, ['--check', 'js/app-shell/unified-app.js'], { stdio: 'inherit' });
console.log('BizOn unified redesign contract passed');
