const fs = require('node:fs');
const assert = require('node:assert/strict');

const vi = fs.readFileSync('play-store/listing/vi-VN.md', 'utf8');
const en = fs.readFileSync('play-store/listing/en-US.md', 'utf8');
const worksheet = fs.readFileSync('play-store/PLAY_CONSOLE_SUBMISSION.md', 'utf8');
const feature = fs.readFileSync('play-store/feature-graphic.html', 'utf8');
const capture = fs.readFileSync('scripts/release/capture-play-store-assets.mjs', 'utf8');
const dataSafety = fs.readFileSync('docs/release/GOOGLE_PLAY_DATA_SAFETY_DRAFT.md', 'utf8');

function section(document, heading) {
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = document.match(new RegExp(`## ${escaped}\\n\\n([^\\n]+)`));
  assert(match, `Missing section: ${heading}`);
  return match[1].trim();
}

const viTitle = section(vi, 'Tên ứng dụng');
const viShort = section(vi, 'Mô tả ngắn');
const enTitle = section(en, 'App name');
const enShort = section(en, 'Short description');

assert(viTitle.length <= 30, `Vietnamese title is ${viTitle.length} characters`);
assert(enTitle.length <= 30, `English title is ${enTitle.length} characters`);
assert(viShort.length <= 80, `Vietnamese short description is ${viShort.length} characters`);
assert(enShort.length <= 80, `English short description is ${enShort.length} characters`);

const publicCopy = `${vi}\n${en}\n${feature}`;
for (const disallowed of [
  /#1|top app|best app|million downloads/i,
  /download now|install now|play now|try now/i,
  /AI[- ]generated|auto[- ]generated|generated by/i,
  /free for a limited time|discount|sale/i
]) {
  assert.doesNotMatch(publicCopy, disallowed);
}

assert.match(feature, /width=1024/);
assert.match(feature, /width:1024px/);
assert.match(feature, /height:500px/);
assert.match(feature, /Mô phỏng · Quyết định · Phản tư/);
assert.doesNotMatch(feature, /Google Play|Android|download|install/i);

for (const route of ['app/release.html', 'game.html', 'app/brand-passport.html', 'app/aibis.html']) {
  assert.equal(fs.existsSync(route), true, `${route} must exist`);
  assert.match(capture, new RegExp(route.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
}

assert.match(capture, /width: 360, height: 640/);
assert.match(capture, /deviceScaleFactor: 3/);
assert.match(capture, /feature-graphic-1024x500\.png/);
assert.match(capture, /app-icon-512\.png/);
assert.match(capture, /alt-text-vi\.json/);

assert.match(worksheet, /vn\.bizon\.simulation/);
assert.match(worksheet, /Internal testing/);
assert.match(worksheet, /root `\/\.well-known\/assetlinks\.json`/);
assert.match(worksheet, /Do not answer “No data collected”/);
assert.match(dataSafety, /collection is optional/i);
assert.match(dataSafety, /Do not state|Assertions not yet allowed/i);

console.log('Play Store submission kit contract passed');
