(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BizOnCountrySources=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const SOURCES=Object.freeze({
  worldBankWdi:Object.freeze({id:'world-bank-wdi',name:'World Development Indicators',owner:'World Bank',url:'https://api.worldbank.org/v2/',access:'public_api',commercialUse:'review_terms',recommendedFor:['marketSize','marketGrowth'],notes:'Use API v2; store indicator code, raw value, year and retrieval date.'}),
  worldGovernance:Object.freeze({id:'world-bank-wgi',name:'Worldwide Governance Indicators',owner:'World Bank',url:'https://www.worldbank.org/en/publication/worldwide-governance-indicators',access:'public_download',commercialUse:'review_terms',recommendedFor:['institutionQuality','politicalRisk'],notes:'Preserve original estimate and uncertainty where available.'}),
  worldBankLpi:Object.freeze({id:'world-bank-lpi',name:'Logistics Performance Index',owner:'World Bank',url:'https://lpi.worldbank.org/',access:'public_download',commercialUse:'review_terms',recommendedFor:['logisticsQuality'],notes:'Not annual; freshness must be displayed.'}),
  wtoTtd:Object.freeze({id:'wto-ttd',name:'Tariff and Trade Data',owner:'World Trade Organization',url:'https://ttd.wto.org/',access:'portal_download',commercialUse:'restricted_check_required',recommendedFor:['tariffPressure'],notes:'Do not redistribute restricted tariff-line data for commercial advantage; prefer permitted aggregates and citations.'}),
  wipoGii:Object.freeze({id:'wipo-gii',name:'Global Innovation Index',owner:'World Intellectual Property Organization',url:'https://www.wipo.int/global_innovation_index/',access:'publication_download',commercialUse:'review_terms',recommendedFor:['digitalReadiness','ipProtection'],notes:'Use documented indicators or country profiles; do not infer legal protection from rank alone.'}),
  ituIct:Object.freeze({id:'itu-ict',name:'ICT Statistics',owner:'International Telecommunication Union',url:'https://www.itu.int/itu-d/sites/statistics/',access:'portal',commercialUse:'review_terms',recommendedFor:['digitalReadiness'],notes:'Prefer direct connectivity indicators where licensing permits.'}),
  expertProtocol:Object.freeze({id:'expert-protocol',name:'BizOn Expert Assessment Protocol',owner:'BizOn',url:'docs/architecture/AIBIS-COUNTRY-PROFILE-MODEL-CARD.md',access:'internal',commercialUse:'allowed',recommendedFor:['culturalDistance','partnerEcosystem','dataRegulationRisk','networkEffects'],notes:'Use only when no validated public indicator is available; report panel size, agreement and review date.'})
});
function get(id){return Object.values(SOURCES).find(s=>s.id===id)||null;}
return Object.freeze({SOURCES,get});});